# Generated by Django 6.0.7 on 2026-10-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Continent",
                "verbose_name_plural": "Continents",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("value_usd", models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="countries",
                        to="listings.continent",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="countries",
                        to="listings.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("city_slug", models.SlugField(max_length=150, unique=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("is_country_archive", models.BooleanField(default=False)),
                (
                    "listings_csv_gz",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "calendar_csv_gz",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "reviews_csv_gz",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("listings_csv", models.URLField(max_length=500)),
                ("reviews_csv", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "neighbourhoods_csv",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "neighbourhoods_geojson",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cities",
                        to="listings.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ("city", "country__continent", "country"),
                "indexes": [
                    models.Index(
                        fields=["country", "city"],
                        name="listings_ci_country_3fb5ff_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="country",
            constraint=models.UniqueConstraint(
                fields=("continent", "slug"), name="uniq_country_slug_per_continent"
            ),
        ),
    ]
